// <auto-generated />
using System;
using JDR.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JDR.Migrations
{
    [DbContext(typeof(BddContext))]
    [Migration("20200509130835_RaceSousRace")]
    partial class RaceSousRace
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JDR.Model.Personnage.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("JDR.Model.Personnage.SousRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("SousRace");
                });

            modelBuilder.Entity("JDR.Model.Statistique.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stats")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.StatUtil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ForStatId")
                        .HasColumnType("int");

                    b.Property<int?>("StatUtileId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForStatId");

                    b.HasIndex("StatUtileId");

                    b.ToTable("StatUtil");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.DeeStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NbDee")
                        .HasColumnType("int");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<int?>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("TailleDee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("StatId");

                    b.ToTable("DeeStat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurRaceStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("StatId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("ValeurRaceStat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurSousRaceStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("SousRaceId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("StatId", "SousRaceId");

                    b.HasIndex("SousRaceId");

                    b.ToTable("ValeurSousRaceStat");
                });

            modelBuilder.Entity("JDR.Model.Personnage.SousRace", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Race", "Race")
                        .WithMany("ListSousRace")
                        .HasForeignKey("RaceId");
                });

            modelBuilder.Entity("JDR.Model.Statistique.StatUtil", b =>
                {
                    b.HasOne("JDR.Model.Statistique.Stat", "ForStat")
                        .WithMany("StatUtils")
                        .HasForeignKey("ForStatId");

                    b.HasOne("JDR.Model.Statistique.Stat", "StatUtile")
                        .WithMany("UsedFor")
                        .HasForeignKey("StatUtileId");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.DeeStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Race", "Race")
                        .WithMany("StatDee")
                        .HasForeignKey("RaceId");

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany()
                        .HasForeignKey("StatId");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurRaceStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Race", "Race")
                        .WithMany("Stat")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("RaceStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurSousRaceStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.SousRace", "SousRace")
                        .WithMany("Stat")
                        .HasForeignKey("SousRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("SousRaceStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
