// <auto-generated />
using System;
using JDR.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JDR.Migrations
{
    [DbContext(typeof(BddContext))]
    [Migration("20200521092111_UserPerso")]
    partial class UserPerso
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JDR.Model.Personnage.Classe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classe");
                });

            modelBuilder.Entity("JDR.Model.Personnage.Perso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClasseId")
                        .HasColumnType("int");

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Lvl")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.Property<int?>("SousRaceId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<bool>("Vivant")
                        .HasColumnType("bit");

                    b.Property<int>("posX")
                        .HasColumnType("int");

                    b.Property<int>("posY")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClasseId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SousRaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Perso");
                });

            modelBuilder.Entity("JDR.Model.Personnage.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Race");
                });

            modelBuilder.Entity("JDR.Model.Personnage.SousRace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("SousRace");
                });

            modelBuilder.Entity("JDR.Model.Statistique.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Definition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stats")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Stat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.StatUtil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ForStatId")
                        .HasColumnType("int");

                    b.Property<int?>("StatUtileId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ForStatId");

                    b.HasIndex("StatUtileId");

                    b.ToTable("StatUtil");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.DeeStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("NbDee")
                        .HasColumnType("int");

                    b.Property<int>("TailleDee")
                        .HasColumnType("int");

                    b.HasKey("StatId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("DeeStat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurBuffStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("PersoId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("StatId", "PersoId");

                    b.HasIndex("PersoId");

                    b.ToTable("ValeurBuffStat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurClasseStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("ClasseId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("StatId", "ClasseId");

                    b.HasIndex("ClasseId");

                    b.ToTable("ValeurClasseStat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurPersoStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("PersoId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("StatId", "PersoId");

                    b.HasIndex("PersoId");

                    b.ToTable("ValeurPersoStat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurRaceStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("StatId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("ValeurRaceStat");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurSousRaceStat", b =>
                {
                    b.Property<int>("StatId")
                        .HasColumnType("int");

                    b.Property<int>("SousRaceId")
                        .HasColumnType("int");

                    b.Property<int>("Valeur")
                        .HasColumnType("int");

                    b.HasKey("StatId", "SousRaceId");

                    b.HasIndex("SousRaceId");

                    b.ToTable("ValeurSousRaceStat");
                });

            modelBuilder.Entity("JDR.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JDR.Model.Personnage.Perso", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Classe", "Classe")
                        .WithMany("ListPerso")
                        .HasForeignKey("ClasseId");

                    b.HasOne("JDR.Model.Personnage.Race", "Race")
                        .WithMany("ListPerso")
                        .HasForeignKey("RaceId");

                    b.HasOne("JDR.Model.Personnage.SousRace", "SousRace")
                        .WithMany("ListPerso")
                        .HasForeignKey("SousRaceId");

                    b.HasOne("JDR.Model.User", "User")
                        .WithMany("Persos")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("JDR.Model.Personnage.SousRace", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Race", "Race")
                        .WithMany("ListSousRace")
                        .HasForeignKey("RaceId");
                });

            modelBuilder.Entity("JDR.Model.Statistique.StatUtil", b =>
                {
                    b.HasOne("JDR.Model.Statistique.Stat", "ForStat")
                        .WithMany("StatUtils")
                        .HasForeignKey("ForStatId");

                    b.HasOne("JDR.Model.Statistique.Stat", "StatUtile")
                        .WithMany("UsedFor")
                        .HasForeignKey("StatUtileId");
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.DeeStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Race", "Race")
                        .WithMany("StatDee")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("DeeStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurBuffStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Perso", "Perso")
                        .WithMany("Buff")
                        .HasForeignKey("PersoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("BuffStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurClasseStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Classe", "Classe")
                        .WithMany("Stat")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("ClasseStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurPersoStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Perso", "Perso")
                        .WithMany("Stats")
                        .HasForeignKey("PersoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("PersoStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurRaceStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.Race", "Race")
                        .WithMany("Stat")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("RaceStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JDR.Model.Statistique.ValeurStat.ValeurSousRaceStat", b =>
                {
                    b.HasOne("JDR.Model.Personnage.SousRace", "SousRace")
                        .WithMany("Stat")
                        .HasForeignKey("SousRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JDR.Model.Statistique.Stat", "Stat")
                        .WithMany("SousRaceStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
